In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
from sklearn.cluster import KMeans 
from sklearn import metrics 
from scipy.spatial.distance import cdist 
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import tree
import graphviz
import os
os.environ["PATH"] += os.pathsep + 'F:/Data Analytics-MS!/Integrated Experiential Learn/Week 5 & 6/release/bin'
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import recall_score

G:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df1 = pd.read_csv('F:/Data Analytics-MS!/Integrated Experiential Learn/Week 5 & 6/indicator_pairs_data updated.csv')
df2 = pd.read_csv('F:/Data Analytics-MS!/Integrated Experiential Learn/Week 5 & 6/obfuscated_demo_data2.csv')

In [3]:
df = pd.merge(df1, df2, on='employee_id', how = 'inner')

In [4]:
df.shape

(132084, 23)

In [5]:
condition = df['alert_category']=='Atomic'
df = df[condition]

In [6]:
df.shape

(92594, 23)

In [23]:
df['classification'].value_counts()

FP         53369
TP/DE      36300
TP/LOW      2702
TP/HIGH      223
Name: classification, dtype: int64

In [7]:
df['Dates'] = pd.to_datetime(df['ge_hire_date']).dt.date
df['Time'] = pd.to_datetime(df['ge_hire_date']).dt.time
df['year'] = pd.DatetimeIndex(df['Dates']).year
df['Tenure'] = df.apply(lambda row: 2020 - row.year, axis = 1) 
df['year'] = df['year'].fillna(0).astype(int)
df['Tenure'] = df['Tenure'].fillna(0).astype(int)

In [8]:
df = df.drop(['alert_id_fk', 'insert_date', 'employee_id', 'score', 'alert_escalation_date', 'ge_hire_date', 'city', 'state_name', 'country_name', 'alert_type', 'alert_category', 'risk_factor', 'avg_score', 'year', 'Time', 'Dates'], axis=1)

In [9]:
df_rf = df.copy()
df_rf2 = df.copy()

In [10]:
#Splitting indicator column into multiple columns
df_rf[['indicator_pairs', '1', '2', '3', '4', '5', '6', '7', '8']] = df_rf.indicator_pairs.str.split("/",expand=True)

In [29]:
export_csv = df_rf.to_csv (r'F:\Data Analytics-MS!\Integrated Experiential Learn\Final Submissions\atomic_alerts_2.csv', index = None, header=True)

In [11]:
#Using Indicators as well

#split dataset in features and target variable
feature_cols = ['owner_name', 'hru', 'person_type', 'person_status', 'Tenure', 'function_group', 'career_band', 'job_function', 'industry_focus_name', 'indicator_pairs', '1', '2', '3', '4', '5', '6', '7', '8']
df_rf['classification'] = np.where((df_rf['classification'] == 'TP/HIGH'), 1, 0)
X1 = df_rf[feature_cols] # Features
y1 = df_rf.classification #Target Variable

#One-hot Encoding
X1 = pd.get_dummies(X1)

#Splitting into training and testing sets
X_train1,X_test1,y_train1,y_test1 = train_test_split(X1,y1,test_size=0.25,random_state=0)

#Training the Algorithm
classifier1 = RandomForestClassifier(n_estimators=20, random_state=0)
classifier1.fit(X_train1, y_train1)
y_pred1 = classifier1.predict(X_test1)

print(confusion_matrix(y_test1,y_pred1))
print(classification_report(y_test1,y_pred1))
print(accuracy_score(y_test1, y_pred1))

[[23076    14]
 [   41    18]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     23090
          1       0.56      0.31      0.40        59

avg / total       1.00      1.00      1.00     23149

0.997624087434


In [15]:
threshold = 0.5

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

In [17]:
accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

0.997624087434


In [18]:
print(confusion_matrix(y_test1,predicted))

[[23076    14]
 [   41    18]]


In [19]:
threshold = 0.25

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.998012873126
[[23058    32]
 [   14    45]]


In [20]:
threshold = 0.167

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.997840079485
[[23053    37]
 [   13    46]]


In [21]:
threshold = 0.023

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.996112143073
[[23009    81]
 [    9    50]]


In [22]:
threshold = 0.001

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.995204976457
[[22986   104]
 [    7    52]]


In [24]:
#Splitting indicator column into multiple columns
df_rf2[['indicator_pairs', '1', '2', '3', '4', '5', '6', '7', '8']] = df_rf2.indicator_pairs.str.split("/",expand=True)

In [25]:
#Using Indicators as well

#split dataset in features and target variable
feature_cols = ['owner_name', 'hru', 'person_type', 'person_status', 'Tenure', 'function_group', 'career_band', 'job_function', 'industry_focus_name', 'indicator_pairs', '1', '2', '3', '4', '5', '6', '7', '8']
df_rf2['classification'] = np.where(((df_rf2['classification'] == 'TP/HIGH') | (df_rf2['classification'] == 'TP/LOW')), 1, 0)
X1 = df_rf2[feature_cols] # Features
y1 = df_rf2.classification #Target Variable

#One-hot Encoding
X1 = pd.get_dummies(X1)

#Splitting into training and testing sets
X_train1,X_test1,y_train1,y_test1 = train_test_split(X1,y1,test_size=0.25,random_state=0)

#Training the Algorithm
classifier1 = RandomForestClassifier(n_estimators=20, random_state=0)
classifier1.fit(X_train1, y_train1)
y_pred1 = classifier1.predict(X_test1)

print(confusion_matrix(y_test1,y_pred1))
print(classification_report(y_test1,y_pred1))
print(accuracy_score(y_test1, y_pred1))

[[22253   207]
 [  226   463]]
             precision    recall  f1-score   support

          0       0.99      0.99      0.99     22460
          1       0.69      0.67      0.68       689

avg / total       0.98      0.98      0.98     23149

0.981295088341


In [26]:
threshold = 0.5

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.98120869152
[[22251   209]
 [  226   463]]


In [27]:
threshold = 0.25

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.981035897879
[[22106   354]
 [   85   604]]


In [28]:
threshold = 0.167

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.970884271459
[[21821   639]
 [   35   654]]


In [29]:
threshold = 0.023

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.95947989114
[[21538   922]
 [   16   673]]


In [30]:
threshold = 0.001

predicted_proba = classifier1.predict_proba(X_test1)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test1, predicted)
print(accuracy)

print(confusion_matrix(y_test1,predicted))

0.958356732472
[[21510   950]
 [   14   675]]
