In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
from sklearn.cluster import KMeans 
from sklearn import metrics 
from scipy.spatial.distance import cdist 
#from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import tree
import graphviz
import os
os.environ["PATH"] += os.pathsep + 'F:/Data Analytics-MS!/Integrated Experiential Learn/Week 5 & 6/release/bin'
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import recall_score
#from imblearn.over_sampling import SMOTE

In [2]:
df1 = pd.read_csv('F:/Data Analytics-MS!/Integrated Experiential Learn/Week 5 & 6/indicator_pairs_data updated.csv')
df2 = pd.read_csv('F:/Data Analytics-MS!/Integrated Experiential Learn/Week 5 & 6/obfuscated_demo_data2.csv')

In [3]:
df = pd.merge(df1, df2, on='employee_id', how = 'inner')

In [4]:
df = df[df['alert_type'] != 'Atomic'] 

In [5]:
df['Dates'] = pd.to_datetime(df['ge_hire_date']).dt.date
df['Time'] = pd.to_datetime(df['ge_hire_date']).dt.time
df['year'] = pd.DatetimeIndex(df['Dates']).year
df['Tenure'] = df.apply(lambda row: 2020 - row.year, axis = 1) 
df['year'] = df['year'].fillna(0).astype(int)
df['Tenure'] = df['Tenure'].fillna(0).astype(int)

In [6]:
df = df.drop(['alert_id_fk', 'insert_date', 'employee_id', 'alert_escalation_date', 'ge_hire_date', 'city', 'state_name', 'country_name', 'alert_category', 'year', 'Time', 'Dates'], axis=1)

In [7]:
#Splitting indicator column into multiple columns
df[['indicator_pairs', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21']] = df.indicator_pairs.str.split("/",expand=True)

In [8]:
dfd = df.copy()
dfw = df.copy()
dfm = df.copy()
dfd = dfd[dfd['alert_type'] != 'Atomic'] 
dfd = dfd[dfd['alert_type'] == 'Daily_Heat'] 
dfw = dfw[dfw['alert_type'] != 'Atomic'] 
dfw = dfw[dfw['alert_type'] == 'Weekly_Heat'] 
dfm = dfm[dfm['alert_type'] != 'Atomic'] 
dfm = dfm[dfm['alert_type'] == 'Monthly_Heat'] 

In [10]:
#Target Variable
dfd['classification'] = np.where(((dfd['classification'] == 'TP/HIGH') | (dfd['classification'] == 'TP/LOW')), 1, 0)
#split dataset in features and target variable
feature_cols = ['score', 'owner_name', 'hru', 'person_type', 'person_status', 'alert_type', 'risk_factor', 'Tenure', 'indicator_pairs']
X = dfd[feature_cols] # Features
y = dfd.classification #Target Variable

#One-hot Encoding
X = pd.get_dummies(X)

#Splitting into training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

#Training the Algorithm

classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[2907   53]
 [  84  232]]
             precision    recall  f1-score   support

          0       0.97      0.98      0.98      2960
          1       0.81      0.73      0.77       316

avg / total       0.96      0.96      0.96      3276

0.958180708181


In [11]:
threshold = 0.5

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.958485958486
[[2905   55]
 [  81  235]]


In [12]:
threshold = 0.25

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.943223443223
[[2831  129]
 [  57  259]]


In [13]:
threshold = 0.167

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.935592185592
[[2792  168]
 [  43  273]]


In [14]:
threshold = 0.023

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.804334554335
[[2335  625]
 [  16  300]]


In [15]:
threshold = 0.001

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.79884004884
[[2317  643]
 [  16  300]]


In [16]:
#Target Variable
dfw['classification'] = np.where(((dfw['classification'] == 'TP/HIGH') | (dfw['classification'] == 'TP/LOW')), 1, 0)
#split dataset in features and target variable
feature_cols = ['score', 'owner_name', 'hru', 'person_type', 'person_status', 'alert_type', 'risk_factor', 'Tenure', 'indicator_pairs']
X = dfw[feature_cols] # Features
y = dfw.classification #Target Variable

#One-hot Encoding
X = pd.get_dummies(X)

#Splitting into training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

#Training the Algorithm

classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[1967   40]
 [  60  270]]
             precision    recall  f1-score   support

          0       0.97      0.98      0.98      2007
          1       0.87      0.82      0.84       330

avg / total       0.96      0.96      0.96      2337

0.957210098417


In [17]:
threshold = 0.5

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.957637997433
[[1967   40]
 [  59  271]]


In [18]:
threshold = 0.25

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.95378690629
[[1928   79]
 [  29  301]]


In [19]:
threshold = 0.167

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.947368421053
[[1902  105]
 [  18  312]]


In [20]:
threshold = 0.023

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.798459563543
[[1538  469]
 [   2  328]]


In [21]:
threshold = 0.001

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.794608472401
[[1529  478]
 [   2  328]]


In [22]:
#Target Variable
dfm['classification'] = np.where(((dfm['classification'] == 'TP/HIGH') | (dfm['classification'] == 'TP/LOW')), 1, 0)
#split dataset in features and target variable
feature_cols = ['score', 'owner_name', 'hru', 'person_type', 'person_status', 'alert_type', 'risk_factor', 'Tenure', 'indicator_pairs']
X = dfm[feature_cols] # Features
y = dfm.classification #Target Variable

#One-hot Encoding
X = pd.get_dummies(X)

#Splitting into training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

#Training the Algorithm

classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[1995   45]
 [  49  197]]
             precision    recall  f1-score   support

          0       0.98      0.98      0.98      2040
          1       0.81      0.80      0.81       246

avg / total       0.96      0.96      0.96      2286

0.958880139983


In [23]:
threshold = 0.5

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.959755030621
[[1992   48]
 [  44  202]]


In [24]:
threshold = 0.25

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.955380577428
[[1962   78]
 [  24  222]]


In [25]:
threshold = 0.167

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.942694663167
[[1928  112]
 [  19  227]]


In [26]:
threshold = 0.023

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.790463692038
[[1565  475]
 [   4  242]]


In [27]:
threshold = 0.001

predicted_proba = classifier.predict_proba(X_test)
predicted = (predicted_proba [:,1] >= threshold).astype('int')

accuracy = accuracy_score(y_test, predicted)
print(accuracy)

print(confusion_matrix(y_test,predicted))

0.7895888014
[[1563  477]
 [   4  242]]
